/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'primary': '#57f1db',
        'primary-container': '#2dd4bf',
        'on-primary': '#003731',
        'on-primary-container': '#00574d',
        'inverse-primary': '#006b5f',
        'primary-fixed': '#62fae3',
        'primary-fixed-dim': '#3cddc7',
        'on-primary-fixed': '#00201c',
        'on-primary-fixed-variant': '#005047',

        'secondary': '#7bd0ff',
        'secondary-container': '#00a6e0',
        'on-secondary': '#00354a',
        'on-secondary-container': '#00374d',
        'secondary-fixed': '#c4e7ff',
        'secondary-fixed-dim': '#7bd0ff',
        'on-secondary-fixed': '#001e2c',
        'on-secondary-fixed-variant': '#004c69',

        'tertiary': '#ffd1b2',
        'tertiary-container': '#ffab6d',
        'on-tertiary': '#4f2500',
        'on-tertiary-container': '#7a3c00',

        'bg-canvas': '#0b1218',
        'surface': '#0a141d',
        'surface-dim': '#0a141d',
        'surface-bright': '#303a44',
        'surface-container-lowest': '#050f18',
        'surface-container-low': '#131d26',
        'surface-container': '#17212a',
        'surface-container-high': '#212b34',
        'surface-container-highest': '#2c3640',
        'surface-border': '#233546',
        'surface-card': '#131d26',
        'surface-variant': '#2c3640',
        'surface-tint': '#3cddc7',

        'text-primary': '#e6edf3',
        'text-muted': '#94a3b8',
        'on-surface': '#d9e4f0',
        'on-surface-variant': '#bacac5',
        'inverse-surface': '#d9e4f0',
        'inverse-on-surface': '#27313b',

        'outline': '#859490',
        'outline-variant': '#3c4a46',

        'status-low': '#4ade80',
        'status-medium': '#fbbf24',
        'status-high': '#f87171',
        'status-low-conf': '#94a3b8',

        'detection-person': '#38bdf8',
        'detection-object': '#fb923c',

        'error': '#ffb4ab',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'on-error': '#690005',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        'data-mono': ['JetBrains Mono', 'monospace'],
        'headline-xl': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'headline-sm': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-section': ['Inter', 'sans-serif'],
      },
      spacing: {
        'gutter-desktop': '1.5rem',
        'gutter': '1rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}